version: '2'

services:
    postgres:
        image: postgres:9.6
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            DATABASE_URL: ${DATABASE_URL}
    php:
        build: docker/php7-fpm
        env_file: ./.env
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
        links:
            - postgres
    nginx:
        build: docker/nginx
        ports:
            - ${WEB_PORT}:80
        volumes_from:
            - php
        volumes:
            - ${LOGS_DIR}/nginx/:/var/log/nginx
